use_frameworks!

target 'PBNetworkingLibraries_Example' do
  pod 'PBNetworkingLibraries', :path => '../'

  target 'PBNetworkingLibraries_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
